# 1. Tell services where the screen is
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec-once = sleep 1 && /usr/lib/xdg-desktop-portal-hyprland
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal-kde
exec-once = sleep 3 && /usr/lib/xdg-desktop-portal --replace
# 2. Polkit authentication agent (handles Bluetooth pairing dialogs, sudo prompts, etc.)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# 3. Start KWallet daemon
exec-once = kwalletd6

# 4. Unlock the wallet using the PAM password
exec-once = /usr/lib/pam_kwallet_init

# 5. Wallpaper
exec-once = awww-daemon
exec-once = sleep 0.5 && awww img --transition-type none -o HDMI-A-1 0x000000
exec-once = sleep 0.5 && awww img --transition-type none -o DP-1 ~/Pictures/Wallpapers/berserk.png
exec-once = sleep 0.5 && awww img --transition-type none -o HDMI-A-2 ~/Pictures/Wallpapers/summer.jpeg

# 6. Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# 7. Notifications
exec-once = mako

# 8. Idle daemon
exec-once = hypridle

# 9. Waybar
exec-once = waybar --config ~/.config/waybar/config-main.jsonc --style ~/.config/waybar/style.css
exec-once = waybar --config ~/.config/waybar/config-oled.jsonc --style ~/.config/waybar/style.css
exec-once = ~/.config/waybar/scripts/oled-autohide.sh