# 1. Tell services where the screen is
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# 2. Start KWallet daemon
exec-once = kwalletd6

# 3. Unlock the wallet using the PAM password
exec-once = /usr/lib/pam_kwallet_init

# 4. Wallpaper
exec-once = awww-daemon
exec-once = sleep 0.5 && awww img --transition-type none -o HDMI-A-1 0x000000
exec-once = sleep 0.5 && awww img --transition-type none -o DP-1 ~/Pictures/Wallpapers/berserk.png
exec-once = sleep 0.5 && awww img --transition-type none -o HDMI-A-2 ~/Pictures/Wallpapers/summer.jpeg

# 5. ydotool daemon (keyboard/mouse simulation)
exec-once = ydotoold

# 6. Lock AI models in RAM
exec-once = ~/.config/hypr/scripts/lock-models-ram.sh

# 6. Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# 7. Waybar
exec-once = waybar --config ~/.config/waybar/config-main.jsonc --style ~/.config/waybar/style.css
exec-once = waybar --config ~/.config/waybar/config-oled.jsonc --style ~/.config/waybar/style.css
exec-once = ~/.config/waybar/scripts/oled-autohide.sh